In [1]:
import numpy as np
import pandas as pd
from keras.layers import Dense, Flatten, LSTM
from keras.models import Sequential
import keras

Using TensorFlow backend.


### Data Preprocessing
#### Prepraring the dependent and independent features

In [2]:
def prepare_data(time_series_data, n_features):
    
    X, y=[], []
    for i in range(len(time_series_data)):
        
        end_index=i+n_features
        if end_index > len(time_series_data)-1:
            break
        seq_x, seq_y=time_series_data[i:end_index], time_series_data[end_index]
        X.append(seq_x)
        y.append(seq_y)
        
    return np.array(X), np.array(y)

In [3]:
time_series=[100, 125, 133, 130, 158, 169, 175, 174, 196, 198, 210]
n_steps=3
X, y = prepare_data(time_series, n_steps)
X, y

(array([[100, 125, 133],
        [125, 133, 130],
        [133, 130, 158],
        [130, 158, 169],
        [158, 169, 175],
        [169, 175, 174],
        [175, 174, 196],
        [174, 196, 198]]),
 array([130, 158, 169, 175, 174, 196, 198, 210]))

In [4]:
X.shape

(8, 3)

In [5]:
n_features=1
X=X.reshape((X.shape[0], X.shape[1], n_features))
X.shape

(8, 3, 1)

In [6]:
X[0]

array([[100],
       [125],
       [133]])

### Building LSTM Model

In [7]:
model=Sequential()
model.add(LSTM(1000, activation='relu', return_sequences=True, input_shape=(n_steps, n_features)))
model.add(LSTM(512, activation='relu', return_sequences=True))
model.add(LSTM(100, activation='relu'))
model.add(Dense(64, activation='relu'))
model.add(Dense(1))

model.compile(loss=keras.losses.mean_absolute_error, optimizer='adam')
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_1 (LSTM)                (None, 3, 1000)           4008000   
_________________________________________________________________
lstm_2 (LSTM)                (None, 3, 512)            3098624   
_________________________________________________________________
lstm_3 (LSTM)                (None, 100)               245200    
_________________________________________________________________
dense_1 (Dense)              (None, 64)                6464      
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 65        
Total params: 7,358,353
Trainable params: 7,358,353
Non-trainable params: 0
_________________________________________________________________


In [ ]:
model.fit(X, y, epochs=500, verbose=1)

Epoch 1/500
8/8 [==============================] - 2s 277ms/step - loss: 176.1480
Epoch 2/500
8/8 [==============================] - 0s 16ms/step - loss: 173.0700
Epoch 3/500
8/8 [==============================] - 0s 15ms/step - loss: 165.0221
Epoch 4/500
8/8 [==============================] - 0s 15ms/step - loss: 145.2456
Epoch 5/500
8/8 [==============================] - 0s 15ms/step - loss: 103.1532
Epoch 6/500
8/8 [==============================] - 0s 15ms/step - loss: 32.1551
Epoch 7/500
8/8 [==============================] - 0s 16ms/step - loss: 86.0070
Epoch 8/500
8/8 [==============================] - 0s 15ms/step - loss: 73.4969
Epoch 9/500
8/8 [==============================] - 0s 15ms/step - loss: 23.8989
Epoch 10/500
8/8 [==============================] - 0s 15ms/step - loss: 26.6595
Epoch 11/500
8/8 [==============================] - 0s 16ms/step - loss: 43.9560
Epoch 12/500
8/8 [==============================] - 0s 15ms/step - loss: 45.5831
Epoch 13/500
8/8 [=============

Epoch 103/500
8/8 [==============================] - 0s 15ms/step - loss: 5.6812
Epoch 104/500
8/8 [==============================] - 0s 15ms/step - loss: 5.4366
Epoch 105/500
8/8 [==============================] - 0s 15ms/step - loss: 5.4032
Epoch 106/500
8/8 [==============================] - 0s 15ms/step - loss: 5.6586
Epoch 107/500
8/8 [==============================] - 0s 15ms/step - loss: 5.5626
Epoch 108/500
8/8 [==============================] - 0s 15ms/step - loss: 5.5540
Epoch 109/500
8/8 [==============================] - 0s 15ms/step - loss: 5.5638
Epoch 110/500
8/8 [==============================] - 0s 15ms/step - loss: 5.3949
Epoch 111/500
8/8 [==============================] - 0s 15ms/step - loss: 5.3306
Epoch 112/500
8/8 [==============================] - 0s 15ms/step - loss: 5.3189
Epoch 113/500
8/8 [==============================] - 0s 15ms/step - loss: 5.2930
Epoch 114/500
8/8 [==============================] - 0s 15ms/step - loss: 5.2561
Epoch 115/500
8/8 [=========

Epoch 204/500
8/8 [==============================] - 0s 15ms/step - loss: 5.7293
Epoch 205/500
8/8 [==============================] - 0s 15ms/step - loss: 4.6714
Epoch 206/500
8/8 [==============================] - 0s 15ms/step - loss: 5.3097
Epoch 207/500
8/8 [==============================] - 0s 15ms/step - loss: 4.1645
Epoch 208/500
8/8 [==============================] - 0s 15ms/step - loss: 5.5568
Epoch 209/500
8/8 [==============================] - 0s 14ms/step - loss: 3.9845
Epoch 210/500
8/8 [==============================] - 0s 15ms/step - loss: 5.4395
Epoch 211/500
8/8 [==============================] - 0s 15ms/step - loss: 4.4624
Epoch 212/500
8/8 [==============================] - 0s 15ms/step - loss: 5.5247
Epoch 213/500
8/8 [==============================] - 0s 15ms/step - loss: 3.9873
Epoch 214/500
8/8 [==============================] - 0s 15ms/step - loss: 3.7729
Epoch 215/500
8/8 [==============================] - 0s 15ms/step - loss: 4.5658
Epoch 216/500
8/8 [=========

### Prediction for next 100 days

In [ ]:
x_input = np.array([196, 210, 215])
temp_input=list(x_input)
lst_output=[]
i=0
while(i<100):
    
    if(len(temp_input)>3):
        x_input=np.array(temp_input[1:])
        print("{} day input {}".format(i,x_input))
        #print(x_input)
        x_input = x_input.reshape((1, n_steps, n_features))
        #print(x_input)
        yhat = model.predict(x_input, verbose=0)
        print("{} day output {}".format(i,yhat))
        temp_input.append(yhat[0][0])
        temp_input=temp_input[1:]
        #print(temp_input)
        lst_output.append(yhat[0][0])
        i=i+1
    else:
        x_input = x_input.reshape((1, n_steps, n_features))
        yhat = model.predict(x_input, verbose=0)
        print(yhat[0])
        temp_input.append(yhat[0][0])
        lst_output.append(yhat[0][0])
        i=i+1
    

print(lst_output)

In [ ]:
time_series

In [ ]:
len(time_series), len(lst_output)

In [ ]:
lst_output

In [ ]:
import matplotlib.pyplot as plt

day_new=np.arange(1, len(time_series)+1)
day_pred=np.arange(len(time_series)+1,len(time_series)+1+100)

In [ ]:
plt.plot(day_new, time_series)
plt.plot(day_pred, lst_output)